name: Show GitHub OIDC token metadata

on:
  workflow_dispatch:

jobs:
  job:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
    - name: Fetch and decode OIDC token
      run: |
        # Trade the internal Actions token for an OIDC token
        # Intentionally set the audience to a value no integration would accept
        IDTOKEN=$(curl "$ACTIONS_ID_TOKEN_REQUEST_URL&audience=api://test" -H "Authorization: Bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" -H "Accept: application/json; api-version=2.0" -H "Content-Type: application/json" -d "{}" | jq -r '.value')
        
        # Show only the first two parts of the JWT token -- metadata, not the secret signature!
        echo $IDTOKEN | jq -R 'split(".") | .[0],.[1] | @base64d | fromjson'
